package com.tripbook.main.global.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
	NOT_FOUND(404, "COMMON-ERR-404", "PAGE_NOTFOUND"),
	BAD_REQUEST(400, "REQ-ERR-400", "BAD_REQUEST"),
	INTER_SERVER_ERROR(500, "COMMON-ERR-500", "INTER_SERVER_ERROR"),
	EMAIL_DUPLICATION(400, "MEMBER-ERR-400", "EMAIL_DUPLICATED"),
	TOKEN_UNAUTHORIZED(401, "TOKEN-ERR-401", "INVALID_TOKEN"),
	FILTER_UNAUTHORIZED(401, "FILTER-ERR-401", "SERVERERROR"),
	FILTER_ACCESS_DENIED(403, "FILTER-ERR-403", "FILTER_ACCESS_DENIED"),
	FILTER_CSRF_ERROR(403, "FILTER-ERR-403", "FILTER_CSRF_ERROR"),
	JWT_INVALID_ERROR(498, "JWT-ERR-498", "INVALID_TOKEN"),
	JWT_EXPIRED_ERROR(401, "JWT-ERR-401", "EXPIRED_TOKEN"),
	JWT_NOTFOUND_ERROR(500, "JWT-ERR-500", "NOTFOUND_TOKEN"),
	JWT_UNSUPPORTED_ERROR(500, "JWT-ERR-500", "UNSUPPORTED_TOKEN"),
	JWT_EMPTY_ERROR(500, "JWT-ERR-500", "INVALID_TOKEN"),
	JWT_UNSUPPORTED_PLATFORM_ERROR(500, "JWT-ERR-500", "UNSUPPORTED_PLATFORM_ERROR"),
	MEMBER_NAME_ERROR(400, "MEMBER-ERR-400", "MEMBER-NAME_ALREADY_EXIST"),
	MEMBER_NOTFOUND(400, "MEMBER-ERR-400", "MEMBER_NOTFOUND"),
	MEMBER_ALREADY_AUTHENTICATE(400, "MEMBER-ERR-400", "MEMBER_ALREADY_AUTHENTICATE"),
	FILE_UNSUPPORTED_ERROR(500, "FILE-ERR-500", "Unsupported_UPLOAD_FILE"),
	FILE_MAXIMUM_ERROR(500, "FILE-ERR-500", "Maximum_Upload_Size_Exceeded");
	private int status;
	private String errorCode;
	private String message;
}