---
springdoc:
  swagger-ui:
    use-root-path: true
domain:
  name: http://127.0.0.1:${server.port}
server.port: 9000
spring:
  security.debug: false
  jpa:
    #    generate-ddl: false
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tripbook
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          auth0:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: UZ7PYWQdxTw85EY1wjUvUXAhNvzJrJER
            client-secret: vEH4FzhtYbMsqDNIfmm1PjCRs2AEtuwJUcq8v1ifsjF5YCE-mzq_2dRsR4FF4F9T
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-af65lj2887m1kztj.us.auth0.com/
            token-uri: https://dev-z2b4bazfo6o536tj.us.auth0.com/userinfo/
---