---
server.port: 9000
spring:
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g0c683083de637b_tripbookdev_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: Tripbookteam07*
  security:
    oauth2:
      client:
        registration:
          auth0:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: UZ7PYWQdxTw85EY1wjUvUXAhNvzJrJER
            client-secret: vEH4FzhtYbMsqDNIfmm1PjCRs2AEtuwJUcq8v1ifsjF5YCE-mzq_2dRsR4FF4F9T
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-af65lj2887m1kztj.us.auth0.com/
            token-uri: https://dev-z2b4bazfo6o536tj.us.auth0.com/userinfo/
cloud:
  oci:
    bucket: tripbook
    namespace: axxqmwxdbwz5
    preAuthenticatedUrl: https://objectstorage.ap-chuncheon-1.oraclecloud.com/p/ea-1Bvx4xgjJafTXZT20GQPP-hjf6GWTgJ3O2qOmkNP89dxvn-aakbnwVpbWtnE_/n/axxqmwxdbwz5/b/tripbook/o/
    configFilePath: classpath:/oci_config
---